# Generated by Django 4.2.6 on 2023-10-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_name', models.CharField(max_length=50)),
                ('days_allowed_in_a_year', models.PositiveIntegerField(default=0)),
                ('days_allowed_in_a_month', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_taken', models.PositiveIntegerField(default=0)),
                ('paid_leave_per_year', models.PositiveIntegerField()),
                ('restricted_days', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.restricteddays')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('slack_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=30, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('leave_status', models.CharField(blank=True, choices=[('APPROVE', 'APPROVE'), ('PENDING', 'PENDING'), ('DENY', 'DENY')], max_length=7, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('Leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.leavetype')),
            ],
        ),
    ]
