# Generated by Django 4.2.6 on 2023-10-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepolicy',
            name='restricted_days_of_week',
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='restricted_days_of_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.restricteddays'),
        ),
    ]
