# Generated by Django 4.2.6 on 2023-10-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='Leave_type',
            new_name='leave_type',
        ),
    ]
