# Generated by Django 4.2.6 on 2023-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_remove_leavepolicy_restricted_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('FULL_DAY', 'FULL_DAY'), ('HALF_DAY', 'HALF_DAY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_status',
            field=models.CharField(blank=True, choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('VACATION', 'VACATION'), ('SICK_LEAVE', 'SICK_LEAVE'), ('MATERNITY_LEAVE', 'MATERNITY_LEAVE')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
