# Generated by Django 4.2.6 on 2023-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leaveapplication_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
