# Generated by Django 4.2.6 on 2023-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_rename_employee_leaveapplication_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='channel_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
