# Generated by Django 4.2.6 on 2023-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_leaveapplication_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_status',
            field=models.CharField(blank=True, choices=[('APPROVE', 'APPROVE'), ('DENY', 'DENY')], max_length=7, null=True),
        ),
    ]
