# Generated by Django 4.2.6 on 2023-10-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_alter_leaveapplication_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='duration_type',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='duration',
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True),
        ),
    ]
