# Generated by Django 4.2.6 on 2023-10-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_remove_leaveapplication_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
