# Generated by Django 4.2.6 on 2023-10-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_alter_restricteddays_day_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='restricted_days_of_week',
        ),
    ]
